[package]
name = "lolasol"
version = "0.1.0"
edition = "2024"

[dependencies]
quanta = "0.12"
hdrhistogram = "7.5"
core_affinity = "0.8"

[[bin]]
name = "ring_buffer_bench"
path = "benchmarks/ring_buffer.rs"

[lib]
name = "lolasol"
path = "src/lib.rs"